# config/cloudinary.yml
development:
  cloud_name: "bsnap"
  api_key:  <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret:  <%= ENV["CLOUDINARY_API_SECRET"] %>

production:
  cloud_name: "bsnap"
  api_key:  <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret:  <%= ENV["CLOUDINARY_API_SECRET"] %>