development:
  # secret_key_base: '4ac32a63423f1286e2b3a792fe8af78cbd694ed4ef192a6b4a3adf68ec1a8da6ec9c7853e1d145a50bb849357dd132ea68feb51d79b3c0316b2d981a9e60558c'
  # FACEBOOK_KEY:  <%= ENV["FACEBOOK_KEY"] %>
  # FACEBOOK_SECRET:  <%= ENV["FACEBOOK_SECRET"] %>
  # GOOGLE_OAUTH2_KEY:  <%= ENV["GOOGLE_OAUTH2_KEY"] %>
  # GOOGLE_OAUTH2_SECRET:  <%= ENV["GOOGLE_OAUTH2_SECRET"] %>
  # SENDGRID_USERNAME:  <%= ENV["SENDGRID_USERNAME"] %>
  # SENDGRID_PASSWORD:  <%= ENV["SENDGRID_PASSWORD"] %>
  CLOUDINARY_API_KEY: '964217779167916'
  CLOUDINARY_API_SECRET: 'CkdIo6QrF2ggrgcsSYK8D_7LGi4'
  FACEBOOK_KEY: '830332180381619'
  FACEBOOK_SECRET: '74c28bb04647b0271e351d1843121757'
  GOOGLE_OAUTH2_KEY: '709181391549-u1cdp418vk9g0ta1c6hlqu1jnpefp4c6.apps.googleusercontent.com'
  GOOGLE_OAUTH2_SECRET: '-0G3-Q3C_eqkAbd9ZBodh6a7'
  SENDGRID_PASSWORD: 'NizhumDe@r05'
  SENDGRID_USERNAME: 'farhan_faruque'
  secret_key_base: '4ac32a63423f1286e2b3a792fe8af78cbd694ed4ef192a6b4a3adf68ec1a8da6ec9c7853e1d145a50bb849357dd132ea68feb51d79b3c0316b2d981a9e60558c'
  #SECRET_KEY_BASE: '4ac32a63423f1286e2b3a792fe8af78cbd694ed4ef192a6b4a3adf68ec1a8da6ec9c7853e1d145a50bb849357dd132ea68feb51d79b3c0316b2d981a9e60558c'

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_KEY:  <%= ENV["FACEBOOK_KEY"] %>
  FACEBOOK_SECRET:  <%= ENV["FACEBOOK_SECRET"] %>
  GOOGLE_OAUTH2_KEY:  <%= ENV["GOOGLE_OAUTH2_KEY"] %>
  GOOGLE_OAUTH2_SECRET:  <%= ENV["GOOGLE_OAUTH2_SECRET"] %>
  SENDGRID_USERNAME:  <%= ENV["SENDGRID_USERNAME"] %>
  SENDGRID_PASSWORD:  <%= ENV["SENDGRID_PASSWORD"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_KEY:  <%= ENV["FACEBOOK_KEY"] %>
  FACEBOOK_SECRET:  <%= ENV["FACEBOOK_SECRET"] %>
  GOOGLE_OAUTH2_KEY:  <%= ENV["GOOGLE_OAUTH2_KEY"] %>
  GOOGLE_OAUTH2_SECRET:  <%= ENV["GOOGLE_OAUTH2_SECRET"] %>
  SENDGRID_USERNAME:  <%= ENV["SENDGRID_USERNAME"] %>
  SENDGRID_PASSWORD:  <%= ENV["SENDGRID_PASSWORD"] %>
