development:
  secret_key_base: '6b4b51636ae29ea6d31e91c8a9ef02f894b74403d6d63df18953a0af86826a2e59c657daf29687b27e1a9396ad6efce6ec8777129fe16f5f37282417a0295586'
  FACEBOOK_KEY: '830332180381619'
  FACEBOOK_SECRET: '74c28bb04647b0271e351d1843121757'
  GOOGLE_OAUTH2_KEY: '709181391549-u1cdp418vk9g0ta1c6hlqu1jnpefp4c6.apps.googleusercontent.com'
  GOOGLE_OAUTH2_SECRET: '-0G3-Q3C_eqkAbd9ZBodh6a7'
  SENDGRID_PASSWORD: 'NizhumDe@r05'
  SENDGRID_USERNAME: 'farhan_faruque'

test:
  secret_key_base:

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_KEY:  <%= ENV["FACEBOOK_KEY"] %>
  FACEBOOK_SECRET:  <%= ENV["FACEBOOK_SECRET"] %>
  GOOGLE_OAUTH2_KEY:  <%= ENV["GOOGLE_OAUTH2_KEY"] %>
  GOOGLE_OAUTH2_SECRET:  <%= ENV["GOOGLE_OAUTH2_SECRET"] %>
  SENDGRID_USERNAME:  <%= ENV["SENDGRID_USERNAME"] %>
  SENDGRID_PASSWORD:  <%= ENV["SENDGRID_PASSWORD"] %>
