development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_KEY:  <%= ENV["FACEBOOK_KEY"] %>
  FACEBOOK_SECRET:  <%= ENV["FACEBOOK_SECRET"] %>
  GOOGLE_OAUTH2_KEY:  <%= ENV["GOOGLE_OAUTH2_KEY"] %>
  GOOGLE_OAUTH2_SECRET:  <%= ENV["GOOGLE_OAUTH2_SECRET"] %>
  SENDGRID_USERNAME:  <%= ENV["SENDGRID_USERNAME"] %>
  SENDGRID_PASSWORD:  <%= ENV["SENDGRID_PASSWORD"] %>

test:
  secret_key_base:

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_KEY:  <%= ENV["FACEBOOK_KEY"] %>
  FACEBOOK_SECRET:  <%= ENV["FACEBOOK_SECRET"] %>
  GOOGLE_OAUTH2_KEY:  <%= ENV["GOOGLE_OAUTH2_KEY"] %>
  GOOGLE_OAUTH2_SECRET:  <%= ENV["GOOGLE_OAUTH2_SECRET"] %>
  SENDGRID_USERNAME:  <%= ENV["SENDGRID_USERNAME"] %>
  SENDGRID_PASSWORD:  <%= ENV["SENDGRID_PASSWORD"] %>
