development:
  secret_key_base:  ENV["SECRET_KEY_BASE"]
  FACEBOOK_KEY:  ENV["FACEBOOK_KEY"]
  FACEBOOK_SECRET:  ENV["FACEBOOK_SECRET"]


test:
  secret_key_base: ENV["SECRET_KEY_BASE"]

production:
  secret_key_base: ENV["SECRET_KEY_BASE"]
